spring:
  application:
    name: liverpool-backend-challenge
  mongodb:
    uri: mongodb://localhost:27017/liverpooldb

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs